version: "3.9"
services:
  redisimq:
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "5005:5005"
    volumes:
      - .:/redim
    working_dir: "/redim"
    command: ["python3", "main.py"]